name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6        
        with:          
          node-version: lts/*
      - name: Create server .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > server/.env
          echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> server/.env
          echo "PORT=3003" >> server/.env
          echo "SECRET=${{ secrets.SECRET }}" >> server/.env
      - name: Install dependencies        
        run: npm install; npm --prefix server install

      - name: Run test        
        run: npm --prefix server run test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6        
        with:          
          node-version: lts/*
      - name: Install dependencies        
        run: npm install; npm --prefix server install; npm --prefix client install
      - name: Check style        
        run: npm run lint --prefix server; npm run lint --prefix client
  
  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6        
        with:          
          node-version: lts/*
      - name: Trigger deployment
        if: ${{ (github.event_name == 'push') && (contains(join(github.event.commits.*.message), '#skip') == false) }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  
  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@1379106025474621571>, the deployment was successful!"
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
  
  notify_failure:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@1379106025474621571>, the deployment failed!"
          title: "deploy"
          description: |
            Build has failed, check the logs for details
            Version `${{ github.event.release.tag_name }}`
            Click [here](${{ github.event.release.html_url }}) to download!
            Commit messages: `${{ join(github.event.commits.*.message) }}`
            Commit hashes: `${{ join(github.event.commits.*.id) }}`
          color: 0xff0000
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
      
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ (contains(join(github.event.commits.*.message), '#skip') == false) }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch